name: Feature Request
description: Propose a new capability or workflow enhancement
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the feature you are proposing.
      placeholder: |
        Example:
        - Add support for GPT as an AI provider
        - Add new workflow profile for API endpoint scaffolding
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature valuable? What problem does it solve?
      placeholder: |
        Example:
        - Needed to support code generation for non-ORM domains.
        - Enables more automation in revision loops.

  - type: textarea
    id: design
    attributes:
      label: Proposed Design (Optional)
      description: Describe how this might work or outline a possible approach.
      placeholder: |
        Examples:
        - Add new subclass of WorkflowProfile
        - Introduce new Strategy for planning provider
        - Add optional flags to existing CLI commands

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you evaluated.
      placeholder: |
        Examples:
        - Reusing existing profiles
        - Using manual execution instead of new automation
